### ISSUE TITLE
`core::arch::{x86, x86_64}::{_mm_getcsr, _mm_setcsr}` deprecated since 1.75.0

### ISSUE THREAD

**Issue by edwloef** [Sin-tel/no_denormals#1]
Should be replaced with inline assembly, as in aarch64.

**Comment by Sin-tel** [comment]
Thanks for report, will fix soon.
Sort of confused why core::arch::x86::_mm_setcsr is *not* deprecated though.

**Comment by edwloef** [comment]
https://doc.rust-lang.org/stable/core/arch/x86/fn._mm_setcsr.html it is deprecated, I just had to edit the title a few times since I forgot x86-32 at first

**Comment by Sin-tel** [comment]
I ended up just slapping an `#[allow(deprecated)]` on there since there is no point re-implementing these exact function in inline assembly.
