### ISSUE TITLE
Consider making no_denormals() unsafe

### ISSUE THREAD

**Issue by HadrienG2** [Sin-tel/no_denormals#2]
**Why?** A non-inlined function call inside of this function is textbook OS ABI violation undefined behavior. And rust further strengthens the rule to make [mere modification of MXCSR UB](https://doc.rust-lang.org/core/arch/x86/fn._mm_setcsr.html) because LLVM does. But one basic design axiom of Rust is that it should not be possible to trigger undefined behavior using only safe code. Therefore this function is unsafe by the book, with a silly safety contract of "don't call this if you don't want UB".

**Why not?** I have enough faith in humanity to believe that no one out there, including in rustc, llvm and libc/libm, should actually be making memory safety critical decisions based on the contents of MXCSR or the rounding behavior of operations on IEEE-754 denormals. So in practical terms, this is just a matter of getting non-deterministic, possibly wrong floating point results, if fancy numerical algorithms from e.g. libm whose correctness relies on precise denormals behavior are called, or super-weird compiler optimization introduce such algorithms even if they were not there in the original source code.

Given the low chances of the latter actually happening in a compiler backend that priorizes bitwise FP reproducibility by default, I believe the kind of people who would use this crate would be okay with a weaker non-safety-critical contract of "don't call libm or any other numerical lib which may potentially rely on the precise behavior of denormals if you care about correctness", even if that's not the actual contract that rustc/llvm operate under.

**Comment by Sin-tel** [comment]
I'm aware of these issues. By marking it safe I'm kind of taking the position you outlined in the 'why not?' section.

The problem remains though, it's basically impossible (in the current semantics of Rust) to alter these flags and not cause UB. If you take this seriously, you should never use this library at all! Marking it as unsafe doesn't really change that.

Of course, I'm open to changing this if people think it is a bad idea.

**Comment by herabit** [comment]
I do think that changing it to be unsafe is critical as there is no real notion of an "unsafe" crate.

At the very least it should only be marked as sound through some optional, not-default cargo feature that documents "enabling this feature is unsound, use at your own risk" much like what the `bytemuck` crate does for implementing `Pod` for raw pointers.

As for why `bytemuck` does that for raw pointers, is a different story that gets us talking about pointer provenance, but that aside, the entrypoints for this crate should be unsafe by default.

It's not as pretty, but it makes it clear that you must be absolutely positively sure that what you are doing is indeed, sound. Which is, part of the appeal of Rust, making it easier to see where undefined behavior may lie.

**Comment by Sin-tel** [comment]
Alright seems reasonable. The API is marked unsafe now for version `0.2.0`.
